// home route
###
GET http://localhost:5000

// get all category
###
GET http://localhost:5000/api/v1/category

// single create category
### 
POST http://localhost:5000/api/v1/category
Content-Type: application/json

{
  "name": "ROOT",
  "description": "root",
  "root": "root",
  "image": "image",
  "orderBy": "1",
  "bestSelling": "0"
}

// single get category
### 
GET http://localhost:5000/api/v1/category/6446a2bf33d92256ae916c2e

// single update category
### 
PUT http://localhost:5000/api/v1/category/6446a39d33d92256ae916c32
Content-Type: application/json

{
  "name": "ROOT",
  "description": "root",
  "root": "root",
  "image": "image",
  "orderBy": "1",
  "bestSelling": "0"
}

// single delete category
### 
DELETE http://localhost:5000/api/v1/category/6446a3ad33d92256ae916c34